FROM node:14.0.0 as build
WORKDIR /appreact
COPY package*.json ./
RUN npm install

COPY . ./
RUN npm run build
FROM nginx:stable-alpine

COPY --from=build /appreact/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]